/**
 *
 *  @file AvailableRecognizers.h
 *
 * Copyright (c)2018 Microblink Ltd. All rights reserved.
 *
 * ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
 * OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
 * WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
 * UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
 * THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
 * REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
 */
#ifndef AVAILABLERECOGNIZERS_H
#define AVAILABLERECOGNIZERS_H

#include "BlinkID/Generic/IdRecognizer.h"
#include "BlinkID/Generic/IdCombinedRecognizer.h"
#include "BlinkID/Barcode/IdBarcodeRecognizer.h"

#endif
