/**
* @file BarcodeDocumentType.h
*
* Copyright (c)2020 Microblink Ltd. All rights reserved.
*
* ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
* OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
* WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
* UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
* THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
* REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
*/
#ifndef DOCUMENT_TYPE_H_INCLUDED
#define DOCUMENT_TYPE_H_INCLUDED

#include <Recognizer/Export.h>

/** Type of the detected document from barcode. */
enum MBBarcodeDocumentType
{
    MB_BARCODE_DOCUMENT_TYPE_NONE,
    MB_BARCODE_DOCUMENT_TYPE_AAMVA_COMPLIANT,
    MB_BARCODE_DOCUMENT_TYPE_ARGENTINA_ID,
    MB_BARCODE_DOCUMENT_TYPE_ARGENTINA_DL,
    MB_BARCODE_DOCUMENT_TYPE_COLOMBIA_ID,
    MB_BARCODE_DOCUMENT_TYPE_COLOMBIA_DL,
    MB_BARCODE_DOCUMENT_TYPE_NIGERIA_VOTER_ID,
    MB_BARCODE_DOCUMENT_TYPE_NIGERIA_DL,
    MB_BARCODE_DOCUMENT_TYPE_PANAMA_ID,
    MB_BARCODE_DOCUMENT_TYPE_SOUTH_AFRICA_ID,
    MB_BARCODE_DOCUMENT_TYPE_COUNT
};

/**
 * @brief Typedef for MBBarcodeDocumentType enum.
 */
MB_EXPORTED_TYPE typedef enum MBBarcodeDocumentType MBBarcodeDocumentType;

#endif
