/**
 *
 *  Created on: 14.12.2018.
 *      Author: dodo
 *
 * Copyright (c)2018 Microblink Ltd. All rights reserved.
 *
 * ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
 * OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
 * WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
 * UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
 * THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
 * REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
 */
#ifndef RECOGNIZER_API_TYPES_H
#define RECOGNIZER_API_TYPES_H

typedef unsigned char MBBool;

#define MB_FALSE 0
#define MB_TRUE  1

typedef unsigned char MBByte;

#endif
