/**
 * @file ClassInfoTypes.h
 *
 * Copyright (c)2020 MicroBlink Ltd. All rights reserved.
 *
 * ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
 * OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
 * WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
 * UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
 * THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
 * REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.
 */

#ifndef CLASSINFOTYPES_H_INCLUDED
#define CLASSINFOTYPES_H_INCLUDED

#include <Recognizer/Export.h>

/** Document country */
enum MBCountry
{
    MB_COUNTRY_NONE                                         = 0,
    MB_COUNTRY_ALBANIA                                      = 1,
    MB_COUNTRY_ALGERIA                                      = 2,
    MB_COUNTRY_ARGENTINA                                    = 3,
    MB_COUNTRY_AUSTRALIA                                    = 4,
    MB_COUNTRY_AUSTRIA                                      = 5,
    MB_COUNTRY_AZERBAIJAN                                   = 6,
    MB_COUNTRY_BAHRAIN                                      = 7,
    MB_COUNTRY_BANGLADESH                                   = 8,
    MB_COUNTRY_BELGIUM                                      = 9,
    MB_COUNTRY_BOSNIA_AND_HERZEGOVINA                       = 10,
    MB_COUNTRY_BRUNEI                                       = 11,
    MB_COUNTRY_BULGARIA                                     = 12,
    MB_COUNTRY_CAMBODIA                                     = 13,
    MB_COUNTRY_CANADA                                       = 14,
    MB_COUNTRY_CHILE                                        = 15,
    MB_COUNTRY_COLOMBIA                                     = 16,
    MB_COUNTRY_COSTA_RICA                                   = 17,
    MB_COUNTRY_CROATIA                                      = 18,
    MB_COUNTRY_CYPRUS                                       = 19,
    MB_COUNTRY_CZECHIA                                      = 20,
    MB_COUNTRY_DENMARK                                      = 21,
    MB_COUNTRY_DOMINICAN_REPUBLIC                           = 22,
    MB_COUNTRY_EGYPT                                        = 23,
    MB_COUNTRY_ESTONIA                                      = 24,
    MB_COUNTRY_FINLAND                                      = 25,
    MB_COUNTRY_FRANCE                                       = 26,
    MB_COUNTRY_GEORGIA                                      = 27,
    MB_COUNTRY_GERMANY                                      = 28,
    MB_COUNTRY_GHANA                                        = 29,
    MB_COUNTRY_GREECE                                       = 30,
    MB_COUNTRY_GUATEMALA                                    = 31,
    MB_COUNTRY_HONG_KONG                                    = 32,
    MB_COUNTRY_HUNGARY                                      = 33,
    MB_COUNTRY_INDIA                                        = 34,
    MB_COUNTRY_INDONESIA                                    = 35,
    MB_COUNTRY_IRELAND                                      = 36,
    MB_COUNTRY_ISRAEL                                       = 37,
    MB_COUNTRY_ITALY                                        = 38,
    MB_COUNTRY_JORDAN                                       = 39,
    MB_COUNTRY_KAZAKHSTAN                                   = 40,
    MB_COUNTRY_KENYA                                        = 41,
    MB_COUNTRY_KOSOVO                                       = 42,
    MB_COUNTRY_KUWAIT                                       = 43,
    MB_COUNTRY_LATVIA                                       = 44,
    MB_COUNTRY_LITHUANIA                                    = 45,
    MB_COUNTRY_MALAYSIA                                     = 46,
    MB_COUNTRY_MALDIVES                                     = 47,
    MB_COUNTRY_MALTA                                        = 48,
    MB_COUNTRY_MAURITIUS                                    = 49,
    MB_COUNTRY_MEXICO                                       = 50,
    MB_COUNTRY_MOROCCO                                      = 51,
    MB_COUNTRY_NETHERLANDS                                  = 52,
    MB_COUNTRY_NEW_ZEALAND                                  = 53,
    MB_COUNTRY_NIGERIA                                      = 54,
    MB_COUNTRY_PAKISTAN                                     = 55,
    MB_COUNTRY_PANAMA                                       = 56,
    MB_COUNTRY_PARAGUAY                                     = 57,
    MB_COUNTRY_PHILIPPINES                                  = 58,
    MB_COUNTRY_POLAND                                       = 59,
    MB_COUNTRY_PORTUGAL                                     = 60,
    MB_COUNTRY_PUERTO_RICO                                  = 61,
    MB_COUNTRY_QATAR                                        = 62,
    MB_COUNTRY_ROMANIA                                      = 63,
    MB_COUNTRY_RUSSIA                                       = 64,
    MB_COUNTRY_SAUDI_ARABIA                                 = 65,
    MB_COUNTRY_SERBIA                                       = 66,
    MB_COUNTRY_SINGAPORE                                    = 67,
    MB_COUNTRY_SLOVAKIA                                     = 68,
    MB_COUNTRY_SLOVENIA                                     = 69,
    MB_COUNTRY_SOUTH_AFRICA                                 = 70,
    MB_COUNTRY_SPAIN                                        = 71,
    MB_COUNTRY_SWEDEN                                       = 72,
    MB_COUNTRY_SWITZERLAND                                  = 73,
    MB_COUNTRY_TAIWAN                                       = 74,
    MB_COUNTRY_THAILAND                                     = 75,
    MB_COUNTRY_TUNISIA                                      = 76,
    MB_COUNTRY_TURKEY                                       = 77,
    MB_COUNTRY_UAE                                          = 78,
    MB_COUNTRY_UGANDA                                       = 79,
    MB_COUNTRY_UK                                           = 80,
    MB_COUNTRY_UKRAINE                                      = 81,
    MB_COUNTRY_USA                                          = 82,
    MB_COUNTRY_VIETNAM                                      = 83,
    MB_COUNTRY_BRAZIL                                       = 84,
    MB_COUNTRY_NORWAY                                       = 85,
    MB_COUNTRY_OMAN                                         = 86,
    MB_COUNTRY_ECUADOR                                      = 87,
    MB_COUNTRY_EL_SALVADOR                                  = 88,
    MB_COUNTRY_SRI_LANKA                                    = 89,
    MB_COUNTRY_PERU                                         = 90,
    MB_COUNTRY_URUGUAY                                      = 91,
    MB_COUNTRY_BAHAMAS                                      = 92,
    MB_COUNTRY_BERMUDA                                      = 93,
    MB_COUNTRY_BOLIVIA                                      = 94,
    MB_COUNTRY_CHINA                                        = 95,
    MB_COUNTRY_EUROPEAN_UNION                               = 96,
    MB_COUNTRY_HAITI                                        = 97,
    MB_COUNTRY_HONDURAS                                     = 98,
    MB_COUNTRY_ICELAND                                      = 99,
    MB_COUNTRY_JAPAN                                        = 100,
    MB_COUNTRY_LUXEMBOURG                                   = 101,
    MB_COUNTRY_MONTENEGRO                                   = 102,
    MB_COUNTRY_NICARAGUA                                    = 103,
    MB_COUNTRY_SOUTH_KOREA                                  = 104,
    MB_COUNTRY_VENEZUELA                                    = 105,
    MB_COUNTRY_AFGHANISTAN                                  = 106,
    MB_COUNTRY_ALAND_ISLANDS                                = 107,
    MB_COUNTRY_AMERICAN_SAMOA                               = 108,
    MB_COUNTRY_ANDORRA                                      = 109,
    MB_COUNTRY_ANGOLA                                       = 110,
    MB_COUNTRY_ANGUILLA                                     = 111,
    MB_COUNTRY_ANTARCTICA                                   = 112,
    MB_COUNTRY_ANTIGUA_AND_BARBUDA                          = 113,
    MB_COUNTRY_ARMENIA                                      = 114,
    MB_COUNTRY_ARUBA                                        = 115,
    MB_COUNTRY_BAILIWICK_OF_GUERNSEY                        = 116,
    MB_COUNTRY_BAILIWICK_OF_JERSEY                          = 117,
    MB_COUNTRY_BARBADOS                                     = 118,
    MB_COUNTRY_BELARUS                                      = 119,
    MB_COUNTRY_BELIZE                                       = 120,
    MB_COUNTRY_BENIN                                        = 121,
    MB_COUNTRY_BHUTAN                                       = 122,
    MB_COUNTRY_BONAIRE_SAINT_EUSTATIUS_AND_SABA             = 123,
    MB_COUNTRY_BOTSWANA                                     = 124,
    MB_COUNTRY_BOUVET_ISLAND                                = 125,
    MB_COUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY               = 126,
    MB_COUNTRY_BURKINA_FASO                                 = 127,
    MB_COUNTRY_BURUNDI                                      = 128,
    MB_COUNTRY_CAMEROON                                     = 129,
    MB_COUNTRY_CAPE_VERDE                                   = 130,
    MB_COUNTRY_CARIBBEAN_NETHERLANDS                        = 131,
    MB_COUNTRY_CAYMAN_ISLANDS                               = 132,
    MB_COUNTRY_CENTRAL_AFRICAN_REPUBLIC                     = 133,
    MB_COUNTRY_CHAD                                         = 134,
    MB_COUNTRY_CHRISTMAS_ISLAND                             = 135,
    MB_COUNTRY_COCOS_ISLANDS                                = 136,
    MB_COUNTRY_COMOROS                                      = 137,
    MB_COUNTRY_CONGO                                        = 138,
    MB_COUNTRY_COOK_ISLANDS                                 = 139,
    MB_COUNTRY_CUBA                                         = 140,
    MB_COUNTRY_CURACAO                                      = 141,
    MB_COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO             = 142,
    MB_COUNTRY_DJIBOUTI                                     = 143,
    MB_COUNTRY_DOMINICA                                     = 144,
    MB_COUNTRY_EAST_TIMOR                                   = 145,
    MB_COUNTRY_EQUATORIAL_GUINEA                            = 146,
    MB_COUNTRY_ERITREA                                      = 147,
    MB_COUNTRY_ETHIOPIA                                     = 148,
    MB_COUNTRY_FALKLAND_ISLANDS                             = 149,
    MB_COUNTRY_FAROE_ISLANDS                                = 150,
    MB_COUNTRY_FEDERATED_STATES_OF_MICRONESIA               = 151,
    MB_COUNTRY_FIJI                                         = 152,
    MB_COUNTRY_FRENCH_GUIANA                                = 153,
    MB_COUNTRY_FRENCH_POLYNESIA                             = 154,
    MB_COUNTRY_FRENCH_SOUTHERN_TERRITORIES                  = 155,
    MB_COUNTRY_GABON                                        = 156,
    MB_COUNTRY_GAMBIA                                       = 157,
    MB_COUNTRY_GIBRALTAR                                    = 158,
    MB_COUNTRY_GREENLAND                                    = 159,
    MB_COUNTRY_GRENADA                                      = 160,
    MB_COUNTRY_GUADELOUPE                                   = 161,
    MB_COUNTRY_GUAM                                         = 162,
    MB_COUNTRY_GUINEA                                       = 163,
    MB_COUNTRY_GUINEA_BISSAU                                = 164,
    MB_COUNTRY_GUYANA                                       = 165,
    MB_COUNTRY_HEARD_ISLAND_AND_MCDONALD_ISLANDS            = 166,
    MB_COUNTRY_IRAN                                         = 167,
    MB_COUNTRY_IRAQ                                         = 168,
    MB_COUNTRY_ISLE_OF_MAN                                  = 169,
    MB_COUNTRY_IVORY_COAST                                  = 170,
    MB_COUNTRY_JAMAICA                                      = 171,
    MB_COUNTRY_KIRIBATI                                     = 172,
    MB_COUNTRY_KYRGYZSTAN                                   = 173,
    MB_COUNTRY_LAOS                                         = 174,
    MB_COUNTRY_LEBANON                                      = 175,
    MB_COUNTRY_LESOTHO                                      = 176,
    MB_COUNTRY_LIBERIA                                      = 177,
    MB_COUNTRY_LIBYA                                        = 178,
    MB_COUNTRY_LIECHTENSTEIN                                = 179,
    MB_COUNTRY_MACAU                                        = 180,
    MB_COUNTRY_MADAGASCAR                                   = 181,
    MB_COUNTRY_MALAWI                                       = 182,
    MB_COUNTRY_MALI                                         = 183,
    MB_COUNTRY_MARSHALL_ISLANDS                             = 184,
    MB_COUNTRY_MARTINIQUE                                   = 185,
    MB_COUNTRY_MAURITANIA                                   = 186,
    MB_COUNTRY_MAYOTTE                                      = 187,
    MB_COUNTRY_MOLDOVA                                      = 188,
    MB_COUNTRY_MONACO                                       = 189,
    MB_COUNTRY_MONGOLIA                                     = 190,
    MB_COUNTRY_MONTSERRAT                                   = 191,
    MB_COUNTRY_MOZAMBIQUE                                   = 192,
    MB_COUNTRY_MYANMAR                                      = 193,
    MB_COUNTRY_NAMIBIA                                      = 194,
    MB_COUNTRY_NAURU                                        = 195,
    MB_COUNTRY_NEPAL                                        = 196,
    MB_COUNTRY_NEW_CALEDONIA                                = 197,
    MB_COUNTRY_NIGER                                        = 198,
    MB_COUNTRY_NIUE                                         = 199,
    MB_COUNTRY_NORFOLK_ISLAND                               = 200,
    MB_COUNTRY_NORTHERN_CYPRUS                              = 201,
    MB_COUNTRY_NORTHERN_MARIANA_ISLANDS                     = 202,
    MB_COUNTRY_NORTH_KOREA                                  = 203,
    MB_COUNTRY_NORTH_MACEDONIA                              = 204,
    MB_COUNTRY_PALAU                                        = 205,
    MB_COUNTRY_PALESTINE                                    = 206,
    MB_COUNTRY_PAPUA_NEW_GUINEA                             = 207,
    MB_COUNTRY_PITCAIRN                                     = 208,
    MB_COUNTRY_REUNION                                      = 209,
    MB_COUNTRY_RWANDA                                       = 210,
    MB_COUNTRY_SAINT_BARTHELEMY                             = 211,
    MB_COUNTRY_SAINT_HELENA_ASCENSION_AND_TRISTIAN_DA_CUNHA = 212,
    MB_COUNTRY_SAINT_KITTS_AND_NEVIS                        = 213,
    MB_COUNTRY_SAINT_LUCIA                                  = 214,
    MB_COUNTRY_SAINT_MARTIN                                 = 215,
    MB_COUNTRY_SAINT_PIERRE_AND_MIQUELON                    = 216,
    MB_COUNTRY_SAINT_VINCENT_AND_THE_GRENADINES             = 217,
    MB_COUNTRY_SAMOA                                        = 218,
    MB_COUNTRY_SAN_MARINO                                   = 219,
    MB_COUNTRY_SAO_TOME_AND_PRINCIPE                        = 220,
    MB_COUNTRY_SENEGAL                                      = 221,
    MB_COUNTRY_SEYCHELLES                                   = 222,
    MB_COUNTRY_SIERRA_LEONE                                 = 223,
    MB_COUNTRY_SINT_MAARTEN                                 = 224,
    MB_COUNTRY_SOLOMON_ISLANDS                              = 225,
    MB_COUNTRY_SOMALIA                                      = 226,
    MB_COUNTRY_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 227,
    MB_COUNTRY_SOUTH_SUDAN                                  = 228,
    MB_COUNTRY_SUDAN                                        = 229,
    MB_COUNTRY_SURINAME                                     = 230,
    MB_COUNTRY_SVALBARD_AND_JAN_MAYEN                       = 231,
    MB_COUNTRY_ESWATINI                                     = 232,
    MB_COUNTRY_SYRIA                                        = 233,
    MB_COUNTRY_TAJIKISTAN                                   = 234,
    MB_COUNTRY_TANZANIA                                     = 235,
    MB_COUNTRY_TOGO                                         = 236,
    MB_COUNTRY_TOKELAU                                      = 237,
    MB_COUNTRY_TONGA                                        = 238,
    MB_COUNTRY_TRINIDAD_AND_TOBAGO                          = 239,
    MB_COUNTRY_TURKMENISTAN                                 = 240,
    MB_COUNTRY_TURKS_AND_CAICOS_ISLANDS                     = 241,
    MB_COUNTRY_TUVALU                                       = 242,
    MB_COUNTRY_UNITED_STATES_MINOR_OUTLYING_ISLANDS         = 243,
    MB_COUNTRY_UZBEKISTAN                                   = 244,
    MB_COUNTRY_VANUATU                                      = 245,
    MB_COUNTRY_VATICAN_CITY                                 = 246,
    MB_COUNTRY_VIRGIN_ISLANDS_BRITISH                       = 247,
    MB_COUNTRY_VIRGIN_ISLANDS_US                            = 248,
    MB_COUNTRY_WALLIS_AND_FUTUNA                            = 249,
    MB_COUNTRY_WESTERN_SAHARA                               = 250,
    MB_COUNTRY_YEMEN                                        = 251,
    MB_COUNTRY_YUGOSLAVIA                                   = 252,
    MB_COUNTRY_ZAMBIA                                       = 253,
    MB_COUNTRY_ZIMBABWE                                     = 254,
    MB_COUNTRY_COUNT                                        = 255,
};

/**
 * @brief Typedef for MBCountry enum.
 */
MB_EXPORTED_TYPE typedef enum MBCountry MBCountry;

/** Document region. */
enum MBRegion
{
    MB_REGION_NONE                         = 0,
    MB_REGION_ALABAMA                      = 1,
    MB_REGION_ALASKA                       = 2,
    MB_REGION_ALBERTA                      = 3,
    MB_REGION_ARIZONA                      = 4,
    MB_REGION_ARKANSAS                     = 5,
    MB_REGION_AUSTRALIAN_CAPITAL_TERRITORY = 6,
    MB_REGION_BRITISH_COLUMBIA             = 7,
    MB_REGION_CALIFORNIA                   = 8,
    MB_REGION_COLORADO                     = 9,
    MB_REGION_CONNECTICUT                  = 10,
    MB_REGION_DELAWARE                     = 11,
    MB_REGION_DISTRICT_OF_COLUMBIA         = 12,
    MB_REGION_FLORIDA                      = 13,
    MB_REGION_GEORGIA                      = 14,
    MB_REGION_HAWAII                       = 15,
    MB_REGION_IDAHO                        = 16,
    MB_REGION_ILLINOIS                     = 17,
    MB_REGION_INDIANA                      = 18,
    MB_REGION_IOWA                         = 19,
    MB_REGION_KANSAS                       = 20,
    MB_REGION_KENTUCKY                     = 21,
    MB_REGION_LOUISIANA                    = 22,
    MB_REGION_MAINE                        = 23,
    MB_REGION_MANITOBA                     = 24,
    MB_REGION_MARYLAND                     = 25,
    MB_REGION_MASSACHUSETTS                = 26,
    MB_REGION_MICHIGAN                     = 27,
    MB_REGION_MINNESOTA                    = 28,
    MB_REGION_MISSISSIPPI                  = 29,
    MB_REGION_MISSOURI                     = 30,
    MB_REGION_MONTANA                      = 31,
    MB_REGION_NEBRASKA                     = 32,
    MB_REGION_NEVADA                       = 33,
    MB_REGION_NEW_BRUNSWICK                = 34,
    MB_REGION_NEW_HAMPSHIRE                = 35,
    MB_REGION_NEW_JERSEY                   = 36,
    MB_REGION_NEW_MEXICO                   = 37,
    MB_REGION_NEW_SOUTH_WALES              = 38,
    MB_REGION_NEW_YORK                     = 39,
    MB_REGION_NORTHERN_TERRITORY           = 40,
    MB_REGION_NORTH_CAROLINA               = 41,
    MB_REGION_NORTH_DAKOTA                 = 42,
    MB_REGION_NOVA_SCOTIA                  = 43,
    MB_REGION_OHIO                         = 44,
    MB_REGION_OKLAHOMA                     = 45,
    MB_REGION_ONTARIO                      = 46,
    MB_REGION_OREGON                       = 47,
    MB_REGION_PENNSYLVANIA                 = 48,
    MB_REGION_QUEBEC                       = 49,
    MB_REGION_QUEENSLAND                   = 50,
    MB_REGION_RHODE_ISLAND                 = 51,
    MB_REGION_SASKATCHEWAN                 = 52,
    MB_REGION_SOUTH_AUSTRALIA              = 53,
    MB_REGION_SOUTH_CAROLINA               = 54,
    MB_REGION_SOUTH_DAKOTA                 = 55,
    MB_REGION_TASMANIA                     = 56,
    MB_REGION_TENNESSEE                    = 57,
    MB_REGION_TEXAS                        = 58,
    MB_REGION_UTAH                         = 59,
    MB_REGION_VERMONT                      = 60,
    MB_REGION_VICTORIA                     = 61,
    MB_REGION_VIRGINIA                     = 62,
    MB_REGION_WASHINGTON                   = 63,
    MB_REGION_WESTERN_AUSTRALIA            = 64,
    MB_REGION_WEST_VIRGINIA                = 65,
    MB_REGION_WISCONSIN                    = 66,
    MB_REGION_WYOMING                      = 67,
    MB_REGION_YUKON                        = 68,
    MB_REGION_CIUDAD_DE_MEXICO             = 69,
    MB_REGION_JALISCO                      = 70,
    MB_REGION_NEWFOUNDLAND_AND_LABRADOR    = 71,
    MB_REGION_NUEVO_LEON                   = 72,
    MB_REGION_BAJA_CALIFORNIA              = 73,
    MB_REGION_CHIHUAHUA                    = 74,
    MB_REGION_GUANAJUATO                   = 75,
    MB_REGION_GUERRERO                     = 76,
    MB_REGION_MEXICO                       = 77,
    MB_REGION_MICHOACAN                    = 78,
    MB_REGION_NEW_YORK_CITY                = 79,
    MB_REGION_TAMAULIPAS                   = 80,
    MB_REGION_VERACRUZ                     = 81,
    MB_REGION_CHIAPAS                      = 82,
    MB_REGION_COAHUILA                     = 83,
    MB_REGION_DURANGO                      = 84,
    MB_REGION_GUERRERO_COCULA              = 85,
    MB_REGION_GUERRERO_JUCHITAN            = 86,
    MB_REGION_GUERRERO_TEPECOACUILCO       = 87,
    MB_REGION_GUERRERO_TLACOAPA            = 88,
    MB_REGION_GUJARAT                      = 89,
    MB_REGION_HIDALGO                      = 90,
    MB_REGION_KARNATAKA                    = 91,
    MB_REGION_KERALA                       = 92,
    MB_REGION_KHYBER_PAKHTUNKHWA           = 93,
    MB_REGION_MADHYA_PRADESH               = 94,
    MB_REGION_MAHARASHTRA                  = 95,
    MB_REGION_MORELOS                      = 96,
    MB_REGION_NAYARIT                      = 97,
    MB_REGION_OAXACA                       = 98,
    MB_REGION_PUEBLA                       = 99,
    MB_REGION_PUNJAB                       = 100,
    MB_REGION_QUERETARO                    = 101,
    MB_REGION_SAN_LUIS_POTOSI              = 102,
    MB_REGION_SINALOA                      = 103,
    MB_REGION_SONORA                       = 104,
    MB_REGION_TABASCO                      = 105,
    MB_REGION_TAMIL_NADU                   = 106,
    MB_REGION_YUCATAN                      = 107,
    MB_REGION_ZACATECAS                    = 108,
    MB_REGION_AGUASCALIENTES               = 109,
    MB_REGION_BAJA_CALIFORNIA_SUR          = 110,
    MB_REGION_CAMPECHE                     = 111,
    MB_REGION_COLIMA                       = 112,
    MB_REGION_QUINTANA_ROO_BENITO_JUAREZ   = 113,
    MB_REGION_QUINTANA_ROO                 = 114,
    MB_REGION_QUINTANA_ROO_SOLIDARIDAD     = 115,
    MB_REGION_TLAXCALA                     = 116,
    MB_REGION_COUNT                        = 117,
};

/**
 * @brief Typedef for MBRegion enum.
 */
MB_EXPORTED_TYPE typedef enum MBRegion MBRegion;

/** Document type. */
enum MBDocumentType
{
    MB_DOCUMENT_TYPE_NONE                       = 0,
    MB_DOCUMENT_TYPE_CONSULAR_ID                = 1,
    MB_DOCUMENT_TYPE_DL                         = 2,
    MB_DOCUMENT_TYPE_DL_PUBLIC_SERVICES_CARD    = 3,
    MB_DOCUMENT_TYPE_EMPLOYMENT_PASS            = 4,
    MB_DOCUMENT_TYPE_FIN_CARD                   = 5,
    MB_DOCUMENT_TYPE_ID                         = 6,
    MB_DOCUMENT_TYPE_MULTIPURPOSE_ID            = 7,
    MB_DOCUMENT_TYPE_MyKad                      = 8,
    MB_DOCUMENT_TYPE_MyKid                      = 9,
    MB_DOCUMENT_TYPE_MyPR                       = 10,
    MB_DOCUMENT_TYPE_MyTentera                  = 11,
    MB_DOCUMENT_TYPE_PAN_CARD                   = 12,
    MB_DOCUMENT_TYPE_PROFESSIONAL_ID            = 13,
    MB_DOCUMENT_TYPE_PUBLIC_SERVICES_CARD       = 14,
    MB_DOCUMENT_TYPE_RESIDENCE_PERMIT           = 15,
    MB_DOCUMENT_TYPE_RESIDENT_ID                = 16,
    MB_DOCUMENT_TYPE_TEMPORARY_RESIDENCE_PERMIT = 17,
    MB_DOCUMENT_TYPE_VOTER_ID                   = 18,
    MB_DOCUMENT_TYPE_WORK_PERMIT                = 19,
    MB_DOCUMENT_TYPE_iKAD                       = 20,
    MB_DOCUMENT_TYPE_MILITARY_ID                = 21,
    MB_DOCUMENT_TYPE_MyKAS                      = 22,
    MB_DOCUMENT_TYPE_SOCIAL_SECURITY_CARD       = 23,
    MB_DOCUMENT_TYPE_HEALTH_INSURANCE_CARD      = 24,
    MB_DOCUMENT_TYPE_PASSPORT                   = 25,
    MB_DOCUMENT_TYPE_S_PASS                     = 26,
    MB_DOCUMENT_TYPE_ADDRESS_CARD               = 27,
    MB_DOCUMENT_TYPE_ALIEN_ID                   = 28,
    MB_DOCUMENT_TYPE_ALIEN_PASSPORT             = 29,
    MB_DOCUMENT_TYPE_GREEN_CARD                 = 30,
    MB_DOCUMENT_TYPE_MINORS_ID                  = 31,
    MB_DOCUMENT_TYPE_POSTAL_ID                  = 32,
    MB_DOCUMENT_TYPE_PROFESSIONAL_DL            = 33,
    MB_DOCUMENT_TYPE_TAX_ID                     = 34,
    MB_DOCUMENT_TYPE_WEAPON_PERMIT              = 35,
    MB_DOCUMENT_TYPE_VISA                       = 36,
    MB_DOCUMENT_TYPE_BORDER_CROSSING_CARD       = 37,
    MB_DOCUMENT_TYPE_DRIVER_CARD                = 38,
    MB_DOCUMENT_TYPE_GLOBAL_ENTRY_CARD          = 39,
    MB_DOCUMENT_TYPE_MyPolis                    = 40,
    MB_DOCUMENT_TYPE_NEXUS_CARD                 = 41,
    MB_DOCUMENT_TYPE_PASSPORT_CARD              = 42,
    MB_DOCUMENT_TYPE_PROOF_OF_AGE_CARD          = 43,
    MB_DOCUMENT_TYPE_REFUGEE_ID                 = 44,
    MB_DOCUMENT_TYPE_TRIBAL_ID                  = 45,
    MB_DOCUMENT_TYPE_VETERAN_ID                 = 46,
    MB_DOCUMENT_TYPE_CITIZENSHIP_CERTIFICATE    = 47,
    MB_DOCUMENT_TYPE_MY_NUMBER_CARD             = 48,
    MB_DOCUMENT_TYPE_COUNT                      = 49,
};

/**
 * @brief Typedef for MBDocumentType enum.
 */
MB_EXPORTED_TYPE typedef enum MBDocumentType MBDocumentType;

#endif
